server:
  port: 8081

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: student-service
    

  
management:
  security:
    enabled: false

logging:
  level:
    com.example.howtodoinjava: DEBUG